on:
  pull_request:
    paths:
      - '*.swift'
      - .github/workflows/ci.yml
jobs:
  build:
    runs-on: macos-11
    strategy:
      matrix:
        xcode: [^12]
        conf: [release, debug]
    steps:
    - uses: actions/checkout@v2
    - uses: mxcl/xcodebuild@v1
      with:
        xcode: ${{ matrix.xcode }}
        configuration: ${{ matrix.conf }}
        warnings-as-errors: true
        action: build
